Add DeleteAccountModal to replace default-styled alert dialog
iron-fish/ironfish-node-app pull request #147
Opened 2024-01-17 17:03 UTC by dguenther

Adds a DeleteAccountModal to replace the default alert styling.

Fixes IFL-2075

2024-01-17 18:21 UTC, skylarrichard123 requested changes
looks good other than that you can delete an account without typing in the account name in the delete confirmation modal, bypassing the point of the modal haha

2024-01-17 23:58 UTC, dguenther commented
Fixed that issue and updated the screenshots to the latest designs. This is waiting for a follow-up on what should display in the "Syncing" state, but I took a stab at it.

2024-01-18 16:22 UTC, dguenther commented
Updated it with the new syncing state.

2024-01-18 22:29 UTC, skylarrichard123 approved these changes

2024-01-18 22:42 UTC, merged