fixes error when quitting app during download
iron-fish/ironfish-node-app pull request #192
Opened 2024-04-17 00:40 UTC by patnir

2024-04-19 18:28 UTC, jowparks commented on main/background.ts
> +    e.preventDefault();
What is `preventDefault`?

2024-04-19 18:30 UTC, jowparks commented on main/api/snapshot/snapshotManager.ts
> +    this.snapshotPromise.reject(
Why are you rejecting on `stop()`? The point of calling this method is to stop, so you are successfully executing method.

2024-04-19 18:38 UTC, patnir commented on main/background.ts
> +    e.preventDefault();
The normal behavior here is to just quit the app. More info here: https://www.electronjs.org/docs/latest/api/app#event-before-quit

So this stops that behavior using preventDefault and stops the download before proceeding the quit the app (app.quit two lines below this one)

2024-04-19 18:38 UTC, patnir commented on main/background.ts
> +    e.preventDefault();
docs on preventDefault: https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault

2024-04-23 20:02 UTC, dguenther requested changes

2024-04-23 20:02 UTC, dguenther commented on main/background.ts
> +    }
Looking at [the source for electron-trpc](https://github.com/jsonnull/electron-trpc/blob/784bbb0cf45b0304c9f55bd9827a51c8dd3a5b6a/packages/electron-trpc/src/main/createIPCHandler.ts#L50), it looks like detachWindow is already called when windows are closed, so I think it's okay to remove our `window.once("closed"` entirely. 

From testing on macOS by clicking the close button, it seems like `window.isDestroyed` returns true at this point, so it ends up not doing anything.

2024-05-28 19:26 UTC, closed without merging