feat: Address book
iron-fish/ironfish-node-app pull request #38
Opened 2023-11-26 16:09 UTC by dgca

![image](https://github.com/iron-fish/ironfish-node-app/assets/3639170/ff96f6a9-d06e-40f4-af89-f4302f573fc8)
<img width="1469" alt="Screenshot 2023-11-26 at 9 07 22 AM" src="https://github.com/iron-fish/ironfish-node-app/assets/3639170/247c3450-aa60-4900-841f-5446067091da">

2023-11-27 17:51 UTC, dguenther requested changes
The extra package and config name would be nice to clean up, but otherwise looks good!

2023-11-27 17:51 UTC, dguenther commented on package.json
> +    "electron-storage": "^1.0.7",
Is this needed? I don't see it used in this PR

2023-11-27 17:51 UTC, dguenther commented on main/api/contacts/utils/getNodeAppBetaContacts.ts
> +  });
This could be in a separate PR, just noting we'll probably want to clean up the old file so it doesn't try to re-migrate contacts. I think it's fine for it to be a one-time migration that removes support for contacts in the old app

2023-11-27 17:51 UTC, dguenther commented on main/api/contacts/index.ts
> +const store = new Store({ schema });
Might want to give the store a name like `contacts` too, just in case we want to use the default file `config` for something at some point.

2023-11-28 16:21 UTC, dgca commented on main/api/contacts/utils/getNodeAppBetaContacts.ts
> +  });
Sounds good! I'll add this once we figure out how we wanna import these guys.

2023-11-28 17:20 UTC, dguenther approved these changes

2023-11-28 17:22 UTC, merged