Set up i18n
iron-fish/ironfish-node-app pull request #48
Opened 2023-11-30 20:47 UTC by dgca

Adds localization to the app!

In order for strings to be picked up for localization, they'll need to be defined using `<FormattedMessage />`. E.g.

```tsx
import { FormattedMessage } from "react-intl";

function Hello() {
  return (
     <Text>
       <FormattedMessage defaultMessage="Hello world!" description="Optional description for translators" />
     </Text>
  );
}
```

For more options, check out the [react-intl docs](https://formatjs.io/docs/react-intl/components#formattedmessage).

---

### Translation process:

2023-11-30 22:31 UTC, dguenther requested changes
Nice, the process is a bit complex but at the application level it seems like it's not too bad!

2023-11-30 22:31 UTC, dguenther commented on renderer/next.config.js
> +  // },
Is this needed for anything?

2023-11-30 23:45 UTC, dgca commented on renderer/next.config.js
> +  // },
Nope!

2023-11-30 23:54 UTC, dgca commented on renderer/intl/compiled-locales/en.json
> +  "/km2Zu": [
Just added the compiled folder to gitignore 👍

2023-12-01 16:28 UTC, dguenther commented on renderer/intl/compiled-locales/en.json
> +  "/km2Zu": [
Nice, I'll take another peek

2023-12-01 18:26 UTC, dguenther approved these changes

2023-12-01 18:26 UTC, merged